# -*- coding: utf-8 -*-
"""ActividadInforme-APGM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vq_UyHTn8iYZBqAjDlGwbM9bxzVlEe11

### Storytelling Avanzado de Ciencia de Datos: Inquilinos
### =================================================
### Este notebook representa un ejemplo de presentación en ciencia de datos.
### Integra análisis exploratorio de datos, transformación de características, modelado comparativo y storytelling visual.

### Importación de las librerías
"""
## pip install pandas numpy seaborn matplotlib scikit-learn
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

"""### Asignación de estilo de los graficos"""

sns.set(style="whitegrid", palette="pastel")

"""###Carga y comprobación inicial de los datos"""

# Revisar la ubicación del dataset (/dataset/ds_inquilinos.csv)
df = pd.read_csv("ds_inquilinos.csv")
df_original = pd.read_csv("ds_inquilinos.csv")

print("Dimensiones del dataset:", df.shape)
df.head()

# Verificamos tipos de datos y valores nulos
# info: Nombre des variables, tipo de variable (dato)
df.info()

# Calculo de valores nulos por columna
print("\nValores nulos por columna:")
print(df.isna().sum())

# Mostrar la cantidad de cada valor en la columna 'ritmo'
# Usamos el DataFrame original para ver las etiquetas de texto
print("Conteo de valores en la columna 'ritmo':")
print(df['ritmo'].value_counts())

# Limpieza de columnas irrelevantes
drop_cols = ['id_inquilino', 'musica_alta', 'animacion']
df = df.drop(columns=drop_cols)

# Transformación de variables categóricas a numéricas
le = LabelEncoder()
# Excluir 'id_inquilino' y cualquier columna no categórica si la hay
cols_to_encode = [col for col in df.columns if df[col].dtype == 'object' and col != 'id_inquilino']

for col in cols_to_encode:
    df[col] = le.fit_transform(df[col])

print("\nDatos después de la transformación de variables categóricas:")
print(df.head())

# Análisis exploratorio de datos (EDA)
# Usar el LabelEncoder para obtener las etiquetas originales
ritmo_labels = df['ritmo'].map({0: 'madrugador', 1: 'nocturno'})

plt.figure(figsize=(4,3))
sns.countplot(x=ritmo_labels, data=df)
plt.title('Distribución general de ritmo')
plt.xlabel('Ritmo') # Add x-axis label
plt.show()

# Relación entre nivel educativo y ritmo
plt.figure(figsize=(6,4))
sns.histplot(df[df['ritmo']==1]['nivel_educativo'], color='blue', label='nocturno', kde=True)
sns.histplot(df[df['ritmo']==0]['nivel_educativo'], color='yellow', label='madrugador', kde=True)
plt.legend()
plt.title('Distribución de ritmo por nivel educativo')
plt.show()

# Crear una tabla de contingencia con proporciones
crosstab_rf_prop = pd.crosstab(df_original['ritmo'], df_original['fumador'], normalize='index')

# Crear el gráfico de barras apiladas
crosstab_rf_prop.plot(kind='bar', stacked=True, figsize=(6, 4), colormap='viridis')
plt.title('Proporción de Fumador por Ritmo')
plt.xlabel('Ritmo')
plt.ylabel('Proporción')
plt.xticks(rotation=0)
plt.legend(title='Fumador')
plt.show()

df.head()

# Subdivición X (variables) y Y (etiquetas)
X = df.drop('ritmo', axis=1)
y = df['ritmo']

X.shape

y.shape

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled

models = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Random Forest': RandomForestClassifier(n_estimators=200, random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=200, random_state=42)
}

results = {}
for name, model in models.items():
    scores = cross_val_score(model, X_scaled, y, cv=5, scoring='accuracy')
    results[name] = (scores.mean(), scores.std())

# Comparativa de desempeño
model_perf = pd.DataFrame(results, index=['Mean Accuracy', 'Std']).T
print("\nDesempeño de los modelos:")
print(model_perf)

plt.figure(figsize=(6,4))
sns.barplot(x=model_perf.index, y=model_perf['Mean Accuracy'])
plt.title('Comparativa de precisión promedio por modelo')
plt.xticks(rotation=15)
plt.show()

# Selección del mejor modelo
best_model = GradientBoostingClassifier(n_estimators=200, random_state=42)
best_model.fit(X_train := X_scaled, y_train := y)
y_pred = best_model.predict(X_scaled)

# importancia de las caracteristicas
# ---------------------------------------------------------
importances = pd.DataFrame({
    'Variable': X.columns,
    'Importancia': best_model.feature_importances_
}).sort_values(by='Importancia', ascending=False)

plt.figure(figsize=(6,4))
sns.barplot(x='Importancia', y='Variable', data=importances)
plt.title('Importancia de las características en el modelo final')
plt.show()

# Storytelling de resultados y conclusiones
print("1 Los factores con mayor impacto en el ritmo es si la persona toca un instrumento, lee y si tiene visitas.")
print("2 El modelo de Gradient Boosting logró la mayor precisión media en validación cruzada (~78.1%) , muy cercano al modelo Logistic Regression.")
print("3 La combinación de factores en la rutina influyen más que los gustos de la persona.")

"""### Conclusiones del Análisis de Ritmo de Inquilinos

Basado en el análisis exploratorio de datos y el modelado predictivo, se obtuvieron las siguientes conclusiones clave:

1.  **Factores Clave del Ritmo:** Las variables con mayor influencia en el ritmo de una persona ('madrugador' o 'nocturno'), según el modelo de Gradient Boosting, son si la persona **toca un instrumento**, si **lee** y si **tiene visitas**. Esto sugiere que los hábitos y rutinas diarias son predictores importantes del ritmo.

2.  **Relación Ritmo y Fumador:** El análisis de la relación entre ritmo y fumador mostró que hay una diferencia en la proporción de fumadores entre las personas "madrugadoras" y "nocturnas". Un mayor porcentaje de personas "nocturnas" son fumadoras en comparación con las "madrugadoras", como se observó en los gráficos de distribución.

3.  **Desempeño del Modelo:** Se compararon tres modelos de clasificación: Regresión Logística, Random Forest y Gradient Boosting. El modelo de **Gradient Boosting** obtuvo la mayor precisión promedio en la validación cruzada (~78.1%), ligeramente superior a la Regresión Logística (\~78.0%). Esto indica que ambos modelos son adecuados para la tarea de predecir el ritmo, con una ligera ventaja para Gradient Boosting.

4.  **Influencia de Factores de Rutina vs. Gustos:** En general, las características relacionadas con la rutina diaria (como tocar un instrumento, leer y tener visitas) tuvieron una mayor importancia para el modelo predictivo que las características relacionadas con gustos o preferencias (como cine, música, comida, etc.). Esto refuerza la idea de que el ritmo está más ligado a los hábitos que a los pasatiempos.

Estas conclusiones proporcionan una visión general de los factores que influyen en el ritmo de los inquilinos y el rendimiento de los modelos predictivos.
"""